=== Backbase/stream-services/stream-dbs-clients/patch/accesscontrol-pandp-query-spec/schema/service-agreements-by-permission-set-pageable-get.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "javaType": "com.backbase.pandp.accesscontrol.query.rest.spec.v2.accesscontrol.accessgroups.serviceagreements.ServiceAgreementByPermissionSet",
    "properties": {
      "id": {
        "$ref": "definitions.json#/definitions/uuid",
        "description": "Service agreement internal id"
      },
      "externalId": {
        "type": "string",
        "description": "Service agreement external id"
      },
      "name": {
        "type": "string",
        "description": "Service agreement name"
      },
      "isMaster": {
        "type": "boolean",
        "description": "Is Service agreement master"
      },
      "regularUserAps": {
        "type": "array",
        "description": "Set of assignable permission sets identified by ids, used for regular users.",
        "items": {
          "type": "number"
        },
        "uniqueItems": true
      },
      "adminUserAps": {
        "type": "array",
        "description": "Set of assignable permission sets identified by ids, used for admin users.",
        "items": {
          "type": "number"
        },
        "uniqueItems": true
      }
    }
  }
}

=== Backbase/stream-services/stream-dbs-clients/patch/accesscontrol-pandp-query-spec/examples/service-agreements-by-permission-set-pageable-get-ex.json
[
  {
    "id": "a1198a20-5a40-4eb7-b47f-a553db920429",
    "externalId": "external-id-1",
    "name": "Broker deal 1",
    "isMaster": true,
    "regularUserAps": [1],
    "adminUserAps": [2]
  },
  {
    "id": "a4258a20-5a40-4eb7-b47f-a553db920429",
    "externalId": "external-id-2",
    "name": "extSA",
    "isMaster": false,
    "regularUserAps": [3, 4, 9],
    "adminUserAps": [4, 7]
  }
]
